apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloud-ingress-operator
  template:
    metadata:
      labels:
        name: cloud-ingress-operator
    spec:
      serviceAccountName: cloud-ingress-operator
      containers:
        - name: cloud-ingress-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cloud-ingress-operator
          imagePullPolicy: Always
          env:
            # "" so that the cache can read objects outside its namespace
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cloud-ingress-operator"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"