kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-ingress-operator
subjects:
- kind: ServiceAccount
  name: cloud-ingress-operator
roleRef:
  kind: Role
  name: cloud-ingress-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-ingress-operator-crb
subjects:
- kind: ServiceAccount
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-ingress-operator-cr